// ============================================================================
// Entities — page-per-entity model (people/places/orgs/topics)
//
// memory.ts handles facts about the user (lives in Melbourne, vegetarian).
// This module handles everyone/everything else in the user's life:
//
//   "Had coffee with Sarah" -> Sarah's person page gets a timeline entry
//   "Acme paid the invoice" -> Acme's org page bumps mention_count
//   "Going back to Brunetti tomorrow" -> Brunetti place page recorded
//
// The compiled_truth on each entity gets injected into prompts so the
// agent answers "how's Sarah?" with actual context instead of "who?".
//
// Pattern inspired by GBrain (Garry Tan): compiled truth above the line,
// append-only timeline below the line, regenerated by background jobs.
// ============================================================================

import { getOpenAIClient, MODEL_MAP, REASONING_EFFORT, isGeminiModel } from './ai/models.ts';
import { geminiSimpleText } from './ai/gemini.ts';
import {
  type Entity,
  type EntityType,
  type UnsummarisedMessage,
  upsertEntity,
  appendEntityTimeline,
  updateEntityCompiledTruth,
  getCoreEntities,
  getEntitiesByIds,
  findEntitiesByNames,
  getEntityTimeline,
} from './state.ts';
import { ENTITY_EXTRACTOR_VERSION } from './env.ts';
import { getAdminClient } from './supabase.ts';
import { contentHash } from './chunker.ts';
import { embedChunks, type ChunkToEmbed } from './embedder.ts';
import { softDeleteSource, insertEmbeddedChunks } from './ingestion-helpers.ts';

// ============================================================================
// Types
// ============================================================================

export interface CandidateEntity {
  entityType: EntityType;
  canonicalName: string;
  aliases: string[];
  /** What the message tells us about this entity right now. Becomes a
      timeline entry; later consolidated into compiled_truth. */
  eventText: string;
  confidence: number;
}

export interface EntityExtractionResult {
  candidatesExtracted: number;
  entitiesUpserted: number;
  timelineEventsAppended: number;
  entitiesRejected: number;
}

// ============================================================================
// Mention extraction (deterministic, zero LLM cost)
// Used for fast entity lookup on every turn, no model call.
// ============================================================================

const MENTION_STOP_WORDS = new Set([
  // Days, months, common acronyms
  'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday',
  'jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'sept', 'oct', 'nov', 'dec',
  'january', 'february', 'march', 'april', 'june', 'july', 'august', 'september',
  'october', 'november', 'december',
  // Common conversational openers / pronouns capitalised at sentence start
  'i', 'i\'m', 'we', 'they', 'you', 'he', 'she', 'it', 'this', 'that', 'these', 'those',
  'today', 'tomorrow', 'yesterday', 'tonight', 'now', 'soon', 'later',
  'yes', 'no', 'ok', 'okay', 'sure', 'thanks', 'thank',
  // Greetings
  'hi', 'hey', 'hello', 'morning', 'evening', 'afternoon', 'night',
  // Common app/service names that aren't entities in the user's life
  'nest', 'siri', 'alexa', 'chatgpt', 'gpt',
]);

const ALIAS_KEYWORDS = [
  'mum', 'mom', 'dad', 'mama', 'papa',
  'wife', 'husband', 'partner', 'gf', 'bf', 'girlfriend', 'boyfriend',
  'son', 'daughter', 'kid', 'kids', 'child', 'children',
  'sister', 'brother', 'sis', 'bro', 'cousin', 'aunt', 'uncle',
  'grandma', 'grandpa', 'nan', 'pop', 'gran',
  'boss', 'colleague', 'coworker', 'teammate',
  'doctor', 'dentist', 'therapist', 'gp', 'lawyer', 'accountant',
  'barber', 'hairdresser', 'trainer', 'cleaner',
];

const PROPER_NOUN_PATTERN = /\b([A-Z][a-z]{2,}(?:\s+[A-Z][a-z]{2,}){0,2})\b/g;
const ALIAS_PATTERN = new RegExp(
  `\\b(?:my\\s+)?(${ALIAS_KEYWORDS.join('|')})\\b`,
  'gi',
);

/**
 * Extract mention candidates from a message: capitalised proper nouns plus
 * relational aliases like "my mum", "the dentist". Returns the surface forms
 * to look up against entity canonical_name + aliases.
 */
export function extractMentionCandidates(message: string): string[] {
  const candidates = new Set<string>();

  for (const match of message.matchAll(PROPER_NOUN_PATTERN)) {
    const name = match[1].trim();
    if (!name) continue;
    if (MENTION_STOP_WORDS.has(name.toLowerCase())) continue;
    candidates.add(name);
    const firstWord = name.split(/\s+/)[0];
    if (firstWord && firstWord.length >= 3) candidates.add(firstWord);
  }

  for (const match of message.matchAll(ALIAS_PATTERN)) {
    const alias = match[1].toLowerCase().trim();
    if (alias) candidates.add(alias);
  }

  return [...candidates];
}

// ============================================================================
// LLM extraction (parallel to extractCandidateMemories)
// ============================================================================

const ENTITY_EXTRACTION_PROMPT = `You are an entity extraction system for a personal AI assistant called Nest. Given a conversation, identify the people, places, organisations, and topics that matter in the user's life. For each, output what this conversation tells us about them.

Respond with ONLY valid JSON in this exact format:
{
  "entities": [
    {
      "entity_type": "person",
      "canonical_name": "Sarah Chen",
      "aliases": ["Sarah"],
      "event_text": "User had coffee with Sarah on Friday and discussed her new job",
      "confidence": 0.85
    }
  ]
}

Allowed entity_type values: person, place, org, topic

Rules:
- canonical_name is the most specific known name. Prefer full names if available, otherwise the form used.
- aliases include short forms ("Sarah" for "Sarah Chen"), nicknames, and relational forms ("mum", "the dentist", "my boss") IF a real proper-noun identity is unknown.
- event_text is a single short sentence stating what THIS conversation reveals about the entity. It will be appended to a timeline; future events will be appended too.
- DO NOT extract the user themselves (those go to memory_items).
- DO NOT extract Nest, the assistant, or any AI tool.
- DO NOT extract trivial mentions ("the weather", "a cafe") unless a specific named place is referenced.
- DO NOT extract pronouns or generic references.
- Lower confidence if the reference is ambiguous (could be more than one person).
- If no meaningful entities were mentioned, return {"entities": []}.
- Be conservative: prefer missing an entity over fabricating one.`;

const VALID_ENTITY_TYPES: Set<string> = new Set(['person', 'place', 'org', 'topic']);

export async function extractCandidateEntities(
  messages: UnsummarisedMessage[],
): Promise<CandidateEntity[]> {
  if (messages.length === 0) return [];

  const conversationText = messages
    .map((m) => {
      const sender = m.role === 'assistant' ? 'Nest' : (m.handle || 'User');
      return `[${sender}]: ${m.content}`;
    })
    .join('\n');

  try {
    const model = MODEL_MAP.orchestration;
    let text: string | undefined;

    if (isGeminiModel(model)) {
      const result = await geminiSimpleText({
        model,
        systemPrompt: ENTITY_EXTRACTION_PROMPT,
        userMessage: conversationText,
        maxOutputTokens: 1024,
      });
      text = result.text;
    } else {
      const client = getOpenAIClient();
      const response = await client.responses.create({
        model,
        instructions: ENTITY_EXTRACTION_PROMPT,
        input: conversationText,
        max_output_tokens: 1024,
        store: false,
        prompt_cache_key: 'nest-entities',
        reasoning: { effort: REASONING_EFFORT.orchestration },
      } as Parameters<typeof client.responses.create>[0]);
      text = response.output_text;
    }

    if (!text) return [];

    let rawText = text.trim();
    const fenceMatch = rawText.match(/```(?:json)?\s*([\s\S]*?)```/);
    if (fenceMatch) rawText = fenceMatch[1].trim();

    const parsed = JSON.parse(rawText);
    const rawEntities = parsed?.entities;
    if (!Array.isArray(rawEntities)) return [];

    return rawEntities
      .filter((e: Record<string, unknown>) =>
        typeof e.canonical_name === 'string' &&
        (e.canonical_name as string).trim().length > 0 &&
        VALID_ENTITY_TYPES.has(e.entity_type as string) &&
        typeof e.event_text === 'string'
      )
      .map((e: Record<string, unknown>) => {
        const aliases = Array.isArray(e.aliases)
          ? (e.aliases as unknown[]).filter((a): a is string => typeof a === 'string' && a.trim().length > 0)
          : [];
        return {
          entityType: e.entity_type as EntityType,
          canonicalName: (e.canonical_name as string).trim(),
          aliases: aliases.map((a) => a.trim()).filter(Boolean),
          eventText: (e.event_text as string).trim(),
          confidence: typeof e.confidence === 'number'
            ? Math.min(1, Math.max(0, e.confidence))
            : 0.6,
        };
      });
  } catch (error) {
    console.error('[entities] Extraction error:', (error as Error).message);
    return [];
  }
}

// ============================================================================
// Embedding — index entity compiled_truth into search_documents
// so it can be retrieved by the same hybrid search pipeline as memories.
// ============================================================================

function entityContextHeader(entity: Entity): string {
  const parts = [
    `Entity: ${entity.canonicalName}`,
    `Type: ${entity.entityType}`,
    `User: ${entity.handle}`,
  ];
  if (entity.aliases.length > 0) {
    parts.push(`Aliases: ${entity.aliases.slice(0, 8).join(', ')}`);
  }
  return parts.join(' | ');
}

async function embedEntity(entity: Entity): Promise<void> {
  if (!entity.compiledTruth || entity.compiledTruth.trim().length === 0) {
    return;
  }

  const supabase = getAdminClient();
  const sourceId = `entity:${entity.id}`;

  try {
    await softDeleteSource(supabase, entity.handle, 'entity_summary', sourceId);

    const header = entityContextHeader(entity);
    const chunk: ChunkToEmbed = {
      text: `${header}\n---\n${entity.compiledTruth}`,
      sourceType: 'entity_summary',
      sourceId,
      title: `${entity.entityType}: ${entity.canonicalName}`,
      chunkIndex: 0,
      contentHash: contentHash('entity_summary', sourceId, 'summary'),
      metadata: {
        entity_id: entity.id,
        entity_type: entity.entityType,
        canonical_name: entity.canonicalName,
        is_core: entity.isCore,
        handle: entity.handle,
      },
    };

    const embedded = await embedChunks([chunk]);
    const { inserted, errors } = await insertEmbeddedChunks(supabase, entity.handle, embedded);
    if (errors > 0) {
      console.warn(`[entities] embedEntity ${entity.id}: ${inserted} inserted, ${errors} errors`);
    }
  } catch (err) {
    console.warn(`[entities] Failed to embed entity ${entity.id}:`, (err as Error).message);
  }
}

function fireAndForgetEmbed(entity: Entity): void {
  embedEntity(entity).catch((err) =>
    console.warn('[entities] Background embed failed:', (err as Error).message)
  );
}

// ============================================================================
// Compiled-truth synthesis (background consolidation)
// Combines existing compiled_truth + recent timeline events into a fresh
// compiled paragraph. Run on a cron, not per-turn.
// ============================================================================

const COMPILED_TRUTH_PROMPT = `You are synthesising a compiled-truth summary about a single entity in a user's life. The compiled truth is one tight paragraph (2-5 sentences, max ~120 words) capturing the most useful current understanding. It will be injected into prompts so an AI assistant can reference this entity naturally.

Rules:
- Lead with the relationship to the user (cofounder, partner, hairdresser, hometown).
- Include the most useful 2-4 stable facts (job, location, key traits).
- Include 1-2 most recent or recurring events when relevant.
- Skip speculation, sentiment unless explicit, and trivial details.
- Never invent facts beyond the supplied evidence.
- Write in third person. No "the user" — refer to the user as "you".
- No headers, no bullet points, no markdown. Plain paragraph only.

Output ONLY the paragraph. No preamble, no JSON.`;

export async function synthesiseCompiledTruth(
  entity: Entity,
  recentEvents: Array<{ eventText: string; eventAt: string }>,
): Promise<string | null> {
  if (recentEvents.length === 0 && !entity.compiledTruth) return null;

  const evidenceLines = recentEvents
    .slice(0, 30)
    .map((e) => `- ${e.eventAt.slice(0, 10)}: ${e.eventText}`)
    .join('\n');

  const userMessage = `Entity: ${entity.canonicalName} (${entity.entityType})
Aliases: ${entity.aliases.length > 0 ? entity.aliases.join(', ') : '(none)'}

Existing compiled truth:
${entity.compiledTruth || '(none — first synthesis)'}

Recent timeline evidence (newest last):
${evidenceLines || '(none)'}`;

  try {
    const model = MODEL_MAP.orchestration;
    let text: string | undefined;

    if (isGeminiModel(model)) {
      const result = await geminiSimpleText({
        model,
        systemPrompt: COMPILED_TRUTH_PROMPT,
        userMessage,
        maxOutputTokens: 400,
      });
      text = result.text;
    } else {
      const client = getOpenAIClient();
      const response = await client.responses.create({
        model,
        instructions: COMPILED_TRUTH_PROMPT,
        input: userMessage,
        max_output_tokens: 400,
        store: false,
        prompt_cache_key: 'nest-entity-truth',
        reasoning: { effort: REASONING_EFFORT.orchestration },
      } as Parameters<typeof client.responses.create>[0]);
      text = response.output_text;
    }

    if (!text) return null;
    const paragraph = text.trim().replace(/\s+/g, ' ');
    return paragraph || null;
  } catch (error) {
    console.error('[entities] Compiled-truth synthesis error:', (error as Error).message);
    return null;
  }
}

// ============================================================================
// Pipeline: extract + upsert + append timeline (called from summariser)
// ============================================================================

export async function processEntityExtraction(
  messages: UnsummarisedMessage[],
  sourceSummaryId?: number | null,
): Promise<EntityExtractionResult> {
  const result: EntityExtractionResult = {
    candidatesExtracted: 0,
    entitiesUpserted: 0,
    timelineEventsAppended: 0,
    entitiesRejected: 0,
  };

  const candidates = await extractCandidateEntities(messages);
  result.candidatesExtracted = candidates.length;
  if (candidates.length === 0) return result;

  const messageIds = messages.map((m) => m.id);
  const handle = messages.find((m) => m.handle)?.handle;
  if (!handle) {
    result.entitiesRejected = candidates.length;
    return result;
  }

  for (const candidate of candidates) {
    if (candidate.confidence < 0.4) {
      result.entitiesRejected += 1;
      continue;
    }

    try {
      const entityId = await upsertEntity({
        handle,
        entityType: candidate.entityType,
        canonicalName: candidate.canonicalName,
        aliases: candidate.aliases,
        metadata: { extractor_version: ENTITY_EXTRACTOR_VERSION },
      });

      if (!entityId) {
        result.entitiesRejected += 1;
        continue;
      }

      result.entitiesUpserted += 1;

      const timelineId = await appendEntityTimeline({
        entityId,
        handle,
        eventText: candidate.eventText,
        sourceKind: 'background_extraction',
        sourceMessageIds: messageIds,
        sourceSummaryId: sourceSummaryId ?? null,
        metadata: { confidence: candidate.confidence },
      });

      if (timelineId) result.timelineEventsAppended += 1;
    } catch (error) {
      console.error('[entities] Upsert/timeline failed:', (error as Error).message);
      result.entitiesRejected += 1;
    }
  }

  return result;
}

// ============================================================================
// Compiled-truth refresh (called from cron / consolidation job)
// ============================================================================

export interface ConsolidationOutcome {
  refreshed: boolean;
  reason?: string;
  compiledTruthLength?: number;
}

/**
 * Regenerate compiled_truth from current timeline + existing truth, then
 * re-embed for retrieval. Caller should already know the handle (cheap to
 * pass in, avoids a timeline lookup just to discover it).
 */
export async function refreshEntityCompiledTruth(
  handle: string,
  entityId: number,
): Promise<ConsolidationOutcome> {
  if (!handle) return { refreshed: false, reason: 'missing_handle' };

  const entities = await getEntitiesByIds(handle, [entityId]);
  if (entities.length === 0) {
    return { refreshed: false, reason: 'entity_not_found' };
  }

  const entity = entities[0];
  const events = await getEntityTimeline(entity.id, 30);
  if (events.length === 0 && !entity.compiledTruth) {
    return { refreshed: false, reason: 'no_evidence' };
  }

  const eventInputs = events.map((e) => ({
    eventText: e.eventText,
    eventAt: e.eventAt,
  }));
  const next = await synthesiseCompiledTruth(entity, eventInputs);
  if (!next) return { refreshed: false, reason: 'synthesis_failed' };

  const importance = computeImportanceScore(entity, events.length);
  await updateEntityCompiledTruth(entity.id, next, importance);

  fireAndForgetEmbed({ ...entity, compiledTruth: next, importanceScore: importance });
  return { refreshed: true, compiledTruthLength: next.length };
}

function computeImportanceScore(entity: Entity, recentEventCount: number): number {
  // Frequency: log-scale on lifetime mentions
  const frequency = Math.min(1, Math.log10(Math.max(1, entity.mentionCount)) / 2);
  // Recency: 1.0 if mentioned today, decays over 60 days
  const daysSince = (Date.now() - new Date(entity.lastMentionedAt).getTime()) / (1000 * 60 * 60 * 24);
  const recency = Math.exp(-daysSince / 30);
  // Recent events: more activity = more important
  const activity = Math.min(1, recentEventCount / 10);
  // Core entities are pinned
  const coreBoost = entity.isCore ? 0.3 : 0;

  return Math.min(1, 0.4 * frequency + 0.3 * recency + 0.2 * activity + coreBoost);
}

// ============================================================================
// Retrieval — combine always-on core + mention-driven + semantic.
// Called per turn from build-context.ts.
// ============================================================================

export interface EntityRetrievalTimings {
  totalMs: number;
  coreMs: number;
  mentionMs: number;
  semanticMs: number;
  embeddingMs: number;
  vectorSearchMs: number;
  hydrateMs: number;
  semanticSkipped: boolean;
}

interface EntityRetrievalParams {
  handle: string;
  currentMessage: string;
  /** Optional pre-computed message embedding to avoid a second embed call. */
  precomputedEmbedding?: number[] | null;
  /** Hard cap on entities returned (token budget enforces below this). */
  maxEntities?: number;
  /** When true, skip the semantic vector search step. */
  skipSemantic?: boolean;
}

export interface EntityRetrievalResult {
  entities: Entity[];
  timings: EntityRetrievalTimings;
}

const DEFAULT_MAX_ENTITIES = 12;

export async function getRelevantEntities(
  params: EntityRetrievalParams,
): Promise<EntityRetrievalResult> {
  const start = Date.now();
  const timings: EntityRetrievalTimings = {
    totalMs: 0,
    coreMs: 0,
    mentionMs: 0,
    semanticMs: 0,
    embeddingMs: 0,
    vectorSearchMs: 0,
    hydrateMs: 0,
    semanticSkipped: !!params.skipSemantic,
  };

  const maxEntities = params.maxEntities ?? DEFAULT_MAX_ENTITIES;
  if (!params.handle) {
    timings.totalMs = Date.now() - start;
    return { entities: [], timings };
  }

  // 1. Always-on core entities
  const corePromise = (async () => {
    const t = Date.now();
    const core = await getCoreEntities(params.handle, 8);
    timings.coreMs = Date.now() - t;
    return core;
  })();

  // 2. Mention-driven lookup (regex on the message)
  const mentionPromise = (async () => {
    const t = Date.now();
    const candidates = extractMentionCandidates(params.currentMessage);
    if (candidates.length === 0) {
      timings.mentionMs = Date.now() - t;
      return [];
    }
    const matched = await findEntitiesByNames(params.handle, candidates);
    timings.mentionMs = Date.now() - t;
    return matched;
  })();

  // 3. Semantic — vector search against entity_summary docs
  const semanticPromise = params.skipSemantic
    ? Promise.resolve([] as number[])
    : (async () => {
        const t = Date.now();
        try {
          const { getEmbedding, vectorString } = await import('./rag-tools.ts');
          const supabase = getAdminClient();

          const embeddingStart = Date.now();
          const embedding = params.precomputedEmbedding ??
            await getEmbedding(params.currentMessage);
          timings.embeddingMs = Date.now() - embeddingStart;

          const vectorStart = Date.now();
          const { data, error } = await supabase.rpc('match_search_documents', {
            p_handle: params.handle,
            query_embedding: vectorString(embedding),
            match_count: 10,
            source_filters: ['entity_summary'],
            min_score: 0.25,
          });
          timings.vectorSearchMs = Date.now() - vectorStart;
          timings.semanticMs = Date.now() - t;

          if (error || !data) return [];
          const ids: number[] = [];
          for (const row of data as Array<{ metadata?: { entity_id?: number } }>) {
            const id = row.metadata?.entity_id;
            if (typeof id === 'number') ids.push(id);
          }
          return ids;
        } catch (err) {
          console.warn(
            '[entities] Semantic search failed:',
            (err as Error).message,
          );
          timings.semanticMs = Date.now() - t;
          return [];
        }
      })();

  const [coreEntities, mentionedEntities, semanticIds] = await Promise.all([
    corePromise,
    mentionPromise,
    semanticPromise,
  ]);

  // 4. Hydrate semantic-only IDs (those not already in core or mention)
  const hydrateStart = Date.now();
  const seen = new Set<number>();
  for (const e of coreEntities) seen.add(e.id);
  for (const e of mentionedEntities) seen.add(e.id);

  const idsToHydrate = semanticIds.filter((id) => !seen.has(id));
  const semanticEntities = idsToHydrate.length > 0
    ? await getEntitiesByIds(params.handle, idsToHydrate)
    : [];
  timings.hydrateMs = Date.now() - hydrateStart;

  // 5. Merge with priority: mentioned > core (in-message context wins) > semantic
  // Then dedupe and cap.
  const ranked: Entity[] = [];
  const finalSeen = new Set<number>();
  const push = (entity: Entity) => {
    if (finalSeen.has(entity.id)) return;
    if (ranked.length >= maxEntities) return;
    ranked.push(entity);
    finalSeen.add(entity.id);
  };

  for (const e of mentionedEntities) push(e);
  for (const e of coreEntities) push(e);
  for (const e of semanticEntities) push(e);

  timings.totalMs = Date.now() - start;
  return { entities: ranked, timings };
}
