// JSON schemas for CRM agent structured outputs (OpenAI strict mode — all properties required).

export const BRIEF_JSON_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "campaign_goal",
    "tone",
    "audience_description",
    "product_focus",
    "layout_preference",
    "include_products",
    "max_recipients",
    "promo_kind",
    "promo_discount_percent",
    "promo_brand",
    "promo_keyword",
    "promo_label",
    "promo_only_on_sale",
    "audience_rules",
  ],
  properties: {
    campaign_goal: { type: "string" },
    tone: { type: "string" },
    audience_description: { type: "string" },
    product_focus: { type: "string" },
    layout_preference: { type: "string", enum: ["classic", "minimal", "editorial"] },
    include_products: { type: "boolean" },
    max_recipients: { type: ["number", "null"] },
    promo_kind: { type: "string", enum: ["none", "percent_off", "on_sale_only"] },
    promo_discount_percent: { type: ["number", "null"] },
    promo_brand: { type: ["string", "null"] },
    promo_keyword: { type: ["string", "null"] },
    promo_label: { type: ["string", "null"] },
    promo_only_on_sale: { type: "boolean" },
    audience_rules: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["type", "value", "label"],
        properties: {
          type: {
            type: "string",
            enum: [
              "min_spend",
              "max_spend",
              "min_visits",
              "max_visits",
              "joined_within_days",
              "joined_before_days",
              "last_purchase_within_days",
              "no_purchase_within_days",
              "inactive_days",
              "purchased_category",
              "purchased_brand",
              "purchased_keyword",
              "lapsed",
              "new_members",
              "high_value",
            ],
          },
          value: { type: ["string", "number", "null"] },
          label: { type: "string" },
        },
      },
    },
  },
} as const;

const BLOCK_ITEM_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "type",
    "title",
    "text",
    "body",
    "align",
    "button_text",
    "url",
    "image_url",
    "alt",
    "height",
  ],
  properties: {
    type: {
      type: "string",
      enum: ["hero", "heading", "text", "button", "image", "products", "spacer", "divider"],
    },
    title: { type: "string" },
    text: { type: "string" },
    body: { type: "string" },
    align: { type: "string", enum: ["left", "center"] },
    button_text: { type: "string" },
    url: { type: "string" },
    image_url: { type: "string" },
    alt: { type: "string" },
    height: { type: "number" },
  },
} as const;

export const COMPOSE_JSON_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "subject",
    "subject_variants",
    "title",
    "body",
    "cta_text",
    "cta_url",
    "footer_text",
    "reasoning",
    "html",
  ],
  properties: {
    subject: { type: "string" },
    subject_variants: { type: "array", items: { type: "string" }, minItems: 1, maxItems: 3 },
    title: { type: "string" },
    body: { type: "string" },
    cta_text: { type: "string" },
    cta_url: { type: "string" },
    footer_text: { type: "string" },
    reasoning: { type: "string" },
    html: { type: "string" },
  },
} as const;

export const REFINE_JSON_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "update_audience",
    "audience_rules",
    "layout_preference",
    "subject",
    "subject_variants",
    "title",
    "body",
    "cta_text",
    "cta_url",
    "footer_text",
    "reasoning",
    "assistant_summary",
    "html",
  ],
  properties: {
    update_audience: { type: "boolean" },
    audience_rules: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["type", "value", "label"],
        properties: {
          type: {
            type: "string",
            enum: [
              "min_spend",
              "max_spend",
              "min_visits",
              "max_visits",
              "joined_within_days",
              "joined_before_days",
              "last_purchase_within_days",
              "no_purchase_within_days",
              "inactive_days",
              "purchased_category",
              "purchased_brand",
              "purchased_keyword",
              "lapsed",
              "new_members",
              "high_value",
            ],
          },
          value: { type: ["string", "number", "null"] },
          label: { type: "string" },
        },
      },
    },
    layout_preference: { type: "string", enum: ["classic", "minimal", "editorial"] },
    subject: { type: "string" },
    subject_variants: { type: "array", items: { type: "string" }, minItems: 1, maxItems: 3 },
    title: { type: "string" },
    body: { type: "string" },
    cta_text: { type: "string" },
    cta_url: { type: "string" },
    footer_text: { type: "string" },
    reasoning: { type: "string" },
    assistant_summary: { type: "string" },
    html: { type: "string" },
  },
} as const;

export const PRODUCT_RANK_JSON_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["ranked_product_ids", "reasoning"],
  properties: {
    ranked_product_ids: { type: "array", items: { type: "string" }, maxItems: 8 },
    reasoning: { type: "string" },
  },
} as const;
