/** Fun, cycling-flavoured titles for the product Ask Genie popup — one picked at random per open. */
export const PRODUCT_GENIE_TITLES = [
  "Ride or pass?",
  "Worth the ride?",
  "Ask before you roll",
  "Gear check?",
  "Worth the climb?",
  "Chain reaction?",
  "Need a second opinion?",
  "Before you buy…",
  "Got gear questions?",
  "Pedal your question",
  "What's the verdict?",
  "Worth the upgrade?",
  "Sunday spin material?",
  "Coffee stop worthy?",
  "N+1 justified?",
  "Shed space for this?",
  "Partner approved?",
  "Mechanic's take?",
  "Group ride ready?",
  "Race day ready?",
  "Commute approved?",
  "Gravel or tarmac?",
  "Aero or comfort?",
  "Carbon or alloy?",
  "Clip in or flat?",
  "Tubeless or bust?",
  "Draft behind this deal?",
  "Strava bait?",
  "PB potential?",
  "Alpine pass worthy?",
  "Rail trail ready?",
  "Bikepacking bait?",
  "Crit weapon?",
  "Zwift approved?",
  "Bunch ride worthy?",
  "Warranty's worth it?",
  "Tyre pressure check",
  "One more bike?",
  "Spoke too soon?",
  "Ready to roll?",
  "Hit the brakes — ask first",
  "Cadence check",
  "The peloton thinks…",
  "Helmets on — ask away",
  "Spin to win?",
  "Draft legal?",
  "Climb category?",
  "QOM potential?",
  "King of the mountain?",
  "Flat or fizzy?",
] as const;

export function pickRandomProductGenieTitle(): string {
  const index = Math.floor(Math.random() * PRODUCT_GENIE_TITLES.length);
  return PRODUCT_GENIE_TITLES[index];
}
