/**
 * Lightspeed R-Series Sale field catalog for the custom table builder.
 *
 * Sources:
 * - https://developers.lightspeedhq.com/retail/endpoints/Sale/
 * - https://developers.lightspeedhq.com/retail/endpoints/SaleLine/
 * - https://developers.lightspeedhq.com/retail/endpoints/SalePayment/
 *
 * Paths resolve against the flattened row produced by `flattenSalesForTable`.
 */

import type { TableBuilderField, TableBuilderGrain } from "./types";

const BOTH: TableBuilderGrain[] = ["sale", "sale_line"];
const SALE_ONLY: TableBuilderGrain[] = ["sale"];
const LINE_ONLY: TableBuilderGrain[] = ["sale_line"];

function f(
  partial: Omit<TableBuilderField, "grains"> & { grains?: TableBuilderGrain[] },
): TableBuilderField {
  return {
    grains: BOTH,
    ...partial,
  };
}

/** All Lightspeed sales-related fields available for custom tables. */
export const SALES_TABLE_FIELDS: TableBuilderField[] = [
  // ── Sale identity ──────────────────────────────────────────
  f({
    key: "sale.saleID",
    path: "sale.saleID",
    label: "Sale ID",
    description: "Unique numerical ID for the sale.",
    type: "text",
    entity: "sale",
    group: "Sale identity",
    idLike: true,
  }),
  f({
    key: "sale.ticketNumber",
    path: "sale.ticketNumber",
    label: "Ticket number",
    description: "POS ticket number shown on the receipt.",
    type: "text",
    entity: "sale",
    group: "Sale identity",
    idLike: true,
  }),
  f({
    key: "sale.referenceNumber",
    path: "sale.referenceNumber",
    label: "Reference number",
    description: "Custom reference from an external system (e.g. webstore).",
    type: "text",
    entity: "sale",
    group: "Sale identity",
  }),
  f({
    key: "sale.referenceNumberSource",
    path: "sale.referenceNumberSource",
    label: "Reference source",
    description: "Name of the external system for the reference number.",
    type: "text",
    entity: "sale",
    group: "Sale identity",
  }),

  // ── Sale status ────────────────────────────────────────────
  f({
    key: "sale.completed",
    path: "sale.completed",
    label: "Completed",
    description: "Whether the sale is completed.",
    type: "boolean",
    entity: "sale",
    group: "Sale status",
  }),
  f({
    key: "sale.archived",
    path: "sale.archived",
    label: "Archived",
    description: "Whether the sale is archived.",
    type: "boolean",
    entity: "sale",
    group: "Sale status",
  }),
  f({
    key: "sale.voided",
    path: "sale.voided",
    label: "Voided",
    description: "Whether the sale has been voided.",
    type: "boolean",
    entity: "sale",
    group: "Sale status",
  }),
  f({
    key: "sale.enablePromotions",
    path: "sale.enablePromotions",
    label: "Promotions enabled",
    description: "Whether promotions run on sale lines.",
    type: "boolean",
    entity: "sale",
    group: "Sale status",
  }),
  f({
    key: "sale.isTaxInclusive",
    path: "sale.isTaxInclusive",
    label: "Tax inclusive",
    description: "Whether prices on the sale are tax inclusive.",
    type: "boolean",
    entity: "sale",
    group: "Sale status",
  }),
  f({
    key: "sale.tipEnabled",
    path: "sale.tipEnabled",
    label: "Tipping enabled",
    description: "Whether tipping is active on this sale.",
    type: "boolean",
    entity: "sale",
    group: "Sale status",
  }),
  f({
    key: "sale.receiptPreference",
    path: "sale.receiptPreference",
    label: "Receipt preference",
    description: "Preferred receipt format (e.g. printed, email).",
    type: "text",
    entity: "sale",
    group: "Sale status",
  }),

  // ── Sale dates ─────────────────────────────────────────────
  f({
    key: "sale.createTime",
    path: "sale.createTime",
    label: "Sale created",
    description: "Date/time the sale was created.",
    type: "date",
    entity: "sale",
    group: "Sale dates",
  }),
  f({
    key: "sale.updateTime",
    path: "sale.updateTime",
    label: "Sale updated",
    description: "Date/time the sale was last updated.",
    type: "date",
    entity: "sale",
    group: "Sale dates",
  }),
  f({
    key: "sale.completeTime",
    path: "sale.completeTime",
    label: "Sale completed",
    description: "Date/time the sale was completed.",
    type: "date",
    entity: "sale",
    group: "Sale dates",
  }),
  f({
    key: "sale.timeStamp",
    path: "sale.timeStamp",
    label: "Sale timestamp",
    description: "Legacy last-modified / completed timestamp.",
    type: "date",
    entity: "sale",
    group: "Sale dates",
  }),

  // ── Sale totals ────────────────────────────────────────────
  f({
    key: "sale.calcSubtotal",
    path: "sale.calcSubtotal",
    label: "Sale subtotal",
    description: "Sale subtotal before discount and tax.",
    type: "number",
    entity: "sale",
    group: "Sale totals",
    format: "currency",
  }),
  f({
    key: "sale.displayableSubtotal",
    path: "sale.displayableSubtotal",
    label: "Sale displayable subtotal",
    type: "number",
    entity: "sale",
    group: "Sale totals",
    format: "currency",
  }),
  f({
    key: "sale.calcDiscount",
    path: "sale.calcDiscount",
    label: "Sale discount total",
    description: "Total amount discounted on the sale.",
    type: "number",
    entity: "sale",
    group: "Sale totals",
    format: "currency",
  }),
  f({
    key: "sale.discountPercent",
    path: "sale.discountPercent",
    label: "Sale discount %",
    description: "Deprecated sale-level discount percent.",
    type: "number",
    entity: "sale",
    group: "Sale totals",
    format: "percent",
  }),
  f({
    key: "sale.calcTotal",
    path: "sale.calcTotal",
    label: "Sale calc total",
    type: "number",
    entity: "sale",
    group: "Sale totals",
    format: "currency",
  }),
  f({
    key: "sale.total",
    path: "sale.total",
    label: "Sale total",
    description: "Subtotal minus discount plus tax.",
    type: "number",
    entity: "sale",
    group: "Sale totals",
    format: "currency",
  }),
  f({
    key: "sale.displayableTotal",
    path: "sale.displayableTotal",
    label: "Sale displayable total",
    description: "Total including gift card deposits.",
    type: "number",
    entity: "sale",
    group: "Sale totals",
    format: "currency",
  }),
  f({
    key: "sale.totalDue",
    path: "sale.totalDue",
    label: "Sale total due",
    type: "number",
    entity: "sale",
    group: "Sale totals",
    format: "currency",
  }),
  f({
    key: "sale.calcPayments",
    path: "sale.calcPayments",
    label: "Sale payments total",
    description: "Sum of all SalePayment amounts.",
    type: "number",
    entity: "sale",
    group: "Sale totals",
    format: "currency",
  }),
  f({
    key: "sale.calcTips",
    path: "sale.calcTips",
    label: "Sale tips total",
    description: "Sum of all SalePayment tip amounts.",
    type: "number",
    entity: "sale",
    group: "Sale totals",
    format: "currency",
  }),
  f({
    key: "sale.balance",
    path: "sale.balance",
    label: "Sale balance",
    description: "Total minus payments.",
    type: "number",
    entity: "sale",
    group: "Sale totals",
    format: "currency",
  }),
  f({
    key: "sale.change",
    path: "sale.change",
    label: "Cash change",
    description: "Cash change given on the sale.",
    type: "number",
    entity: "sale",
    group: "Sale totals",
    format: "currency",
  }),

  // ── Sale tax ───────────────────────────────────────────────
  f({
    key: "sale.tax1Rate",
    path: "sale.tax1Rate",
    label: "Sale tax 1 rate",
    type: "number",
    entity: "sale",
    group: "Sale tax",
    format: "percent",
  }),
  f({
    key: "sale.tax2Rate",
    path: "sale.tax2Rate",
    label: "Sale tax 2 rate",
    type: "number",
    entity: "sale",
    group: "Sale tax",
    format: "percent",
  }),
  f({
    key: "sale.calcTax1",
    path: "sale.calcTax1",
    label: "Sale tax 1 total",
    type: "number",
    entity: "sale",
    group: "Sale tax",
    format: "currency",
  }),
  f({
    key: "sale.calcTax2",
    path: "sale.calcTax2",
    label: "Sale tax 2 total",
    type: "number",
    entity: "sale",
    group: "Sale tax",
    format: "currency",
  }),
  f({
    key: "sale.taxTotal",
    path: "sale.taxTotal",
    label: "Sale tax total",
    type: "number",
    entity: "sale",
    group: "Sale tax",
    format: "currency",
  }),
  f({
    key: "sale.calcTaxable",
    path: "sale.calcTaxable",
    label: "Sale taxable subtotal",
    type: "number",
    entity: "sale",
    group: "Sale tax",
    format: "currency",
  }),
  f({
    key: "sale.calcNonTaxable",
    path: "sale.calcNonTaxable",
    label: "Sale non-taxable subtotal",
    type: "number",
    entity: "sale",
    group: "Sale tax",
    format: "currency",
  }),
  f({
    key: "sale.taxCategoryID",
    path: "sale.taxCategoryID",
    label: "Sale tax category ID",
    type: "text",
    entity: "sale",
    group: "Sale tax",
    idLike: true,
  }),

  // ── Sale cost ──────────────────────────────────────────────
  f({
    key: "sale.calcAvgCost",
    path: "sale.calcAvgCost",
    label: "Sale average cost",
    description: "Total average cost of all lines.",
    type: "number",
    entity: "sale",
    group: "Sale cost",
    format: "currency",
  }),
  f({
    key: "sale.calcFIFOCost",
    path: "sale.calcFIFOCost",
    label: "Sale FIFO cost",
    description: "Total FIFO cost of all lines.",
    type: "number",
    entity: "sale",
    group: "Sale cost",
    format: "currency",
  }),

  // ── Sale foreign keys ──────────────────────────────────────
  f({
    key: "sale.customerID",
    path: "sale.customerID",
    label: "Sale customer ID",
    type: "text",
    entity: "sale",
    group: "Sale links",
    idLike: true,
  }),
  f({
    key: "sale.employeeID",
    path: "sale.employeeID",
    label: "Sale employee ID",
    type: "text",
    entity: "sale",
    group: "Sale links",
    idLike: true,
  }),
  f({
    key: "sale.tipEmployeeID",
    path: "sale.tipEmployeeID",
    label: "Tip employee ID",
    type: "text",
    entity: "sale",
    group: "Sale links",
    idLike: true,
  }),
  f({
    key: "sale.registerID",
    path: "sale.registerID",
    label: "Register ID",
    type: "text",
    entity: "sale",
    group: "Sale links",
    idLike: true,
  }),
  f({
    key: "sale.shopID",
    path: "sale.shopID",
    label: "Shop ID",
    type: "text",
    entity: "sale",
    group: "Sale links",
    idLike: true,
  }),
  f({
    key: "sale.discountID",
    path: "sale.discountID",
    label: "Sale discount ID",
    description: "Deprecated sale-level discount ID.",
    type: "text",
    entity: "sale",
    group: "Sale links",
    idLike: true,
  }),
  f({
    key: "sale.quoteID",
    path: "sale.quoteID",
    label: "Quote ID",
    type: "text",
    entity: "sale",
    group: "Sale links",
    idLike: true,
  }),
  f({
    key: "sale.shipToID",
    path: "sale.shipToID",
    label: "Ship-to ID",
    type: "text",
    entity: "sale",
    group: "Sale links",
    idLike: true,
  }),

  // ── Sale line identity ─────────────────────────────────────
  f({
    key: "line.saleLineID",
    path: "line.saleLineID",
    label: "Sale line ID",
    type: "text",
    entity: "saleLine",
    group: "Sale line identity",
    grains: LINE_ONLY,
    idLike: true,
  }),
  f({
    key: "line.saleID",
    path: "line.saleID",
    label: "Line sale ID",
    type: "text",
    entity: "saleLine",
    group: "Sale line identity",
    grains: LINE_ONLY,
    idLike: true,
  }),
  f({
    key: "line.lineType",
    path: "line.lineType",
    label: "Line type",
    description: "Descriptor such as item_fee or item_fee_refund.",
    type: "text",
    entity: "saleLine",
    group: "Sale line identity",
    grains: LINE_ONLY,
  }),
  f({
    key: "line.createTime",
    path: "line.createTime",
    label: "Line created",
    type: "date",
    entity: "saleLine",
    group: "Sale line identity",
    grains: LINE_ONLY,
  }),
  f({
    key: "line.timeStamp",
    path: "line.timeStamp",
    label: "Line timestamp",
    type: "date",
    entity: "saleLine",
    group: "Sale line identity",
    grains: LINE_ONLY,
  }),

  // ── Sale line qty & price ──────────────────────────────────
  f({
    key: "line.unitQuantity",
    path: "line.unitQuantity",
    label: "Quantity",
    description: "Units sold (negative for refunds).",
    type: "number",
    entity: "saleLine",
    group: "Sale line pricing",
    grains: LINE_ONLY,
    format: "number",
  }),
  f({
    key: "line.unitPrice",
    path: "line.unitPrice",
    label: "Unit price",
    description: "Unit price after price rules.",
    type: "number",
    entity: "saleLine",
    group: "Sale line pricing",
    grains: LINE_ONLY,
    format: "currency",
  }),
  f({
    key: "line.normalUnitPrice",
    path: "line.normalUnitPrice",
    label: "Normal unit price",
    description: "Unit price before price rules.",
    type: "number",
    entity: "saleLine",
    group: "Sale line pricing",
    grains: LINE_ONLY,
    format: "currency",
  }),
  f({
    key: "line.displayableUnitPrice",
    path: "line.displayableUnitPrice",
    label: "Displayable unit price",
    type: "number",
    entity: "saleLine",
    group: "Sale line pricing",
    grains: LINE_ONLY,
    format: "currency",
  }),
  f({
    key: "line.displayableSubtotal",
    path: "line.displayableSubtotal",
    label: "Line displayable subtotal",
    type: "number",
    entity: "saleLine",
    group: "Sale line pricing",
    grains: LINE_ONLY,
    format: "currency",
  }),
  f({
    key: "line.calcSubtotal",
    path: "line.calcSubtotal",
    label: "Line subtotal",
    description: "unitQuantity × unitPrice.",
    type: "number",
    entity: "saleLine",
    group: "Sale line pricing",
    grains: LINE_ONLY,
    format: "currency",
  }),
  f({
    key: "line.calcTotal",
    path: "line.calcTotal",
    label: "Line total",
    type: "number",
    entity: "saleLine",
    group: "Sale line pricing",
    grains: LINE_ONLY,
    format: "currency",
  }),

  // ── Sale line discounts ────────────────────────────────────
  f({
    key: "line.discountAmount",
    path: "line.discountAmount",
    label: "Line discount amount",
    type: "number",
    entity: "saleLine",
    group: "Sale line discounts",
    grains: LINE_ONLY,
    format: "currency",
  }),
  f({
    key: "line.discountPercent",
    path: "line.discountPercent",
    label: "Line discount %",
    type: "number",
    entity: "saleLine",
    group: "Sale line discounts",
    grains: LINE_ONLY,
    format: "percent",
  }),
  f({
    key: "line.calcLineDiscount",
    path: "line.calcLineDiscount",
    label: "Line-level discount",
    type: "number",
    entity: "saleLine",
    group: "Sale line discounts",
    grains: LINE_ONLY,
    format: "currency",
  }),
  f({
    key: "line.calcTransactionDiscount",
    path: "line.calcTransactionDiscount",
    label: "Transaction discount on line",
    type: "number",
    entity: "saleLine",
    group: "Sale line discounts",
    grains: LINE_ONLY,
    format: "currency",
  }),
  f({
    key: "line.discountID",
    path: "line.discountID",
    label: "Line discount ID",
    type: "text",
    entity: "saleLine",
    group: "Sale line discounts",
    grains: LINE_ONLY,
    idLike: true,
  }),
  f({
    key: "line.discountName",
    path: "line.discountName",
    label: "Line discount name",
    description: "Name from the Discount relation on the line.",
    type: "text",
    entity: "discount",
    group: "Sale line discounts",
    grains: LINE_ONLY,
  }),

  // ── Sale line tax ──────────────────────────────────────────
  f({
    key: "line.tax",
    path: "line.tax",
    label: "Line taxable",
    description: "Whether the line is taxed.",
    type: "boolean",
    entity: "saleLine",
    group: "Sale line tax",
    grains: LINE_ONLY,
  }),
  f({
    key: "line.tax1Rate",
    path: "line.tax1Rate",
    label: "Line tax 1 rate",
    type: "number",
    entity: "saleLine",
    group: "Sale line tax",
    grains: LINE_ONLY,
    format: "percent",
  }),
  f({
    key: "line.tax2Rate",
    path: "line.tax2Rate",
    label: "Line tax 2 rate",
    type: "number",
    entity: "saleLine",
    group: "Sale line tax",
    grains: LINE_ONLY,
    format: "percent",
  }),
  f({
    key: "line.calcTax1",
    path: "line.calcTax1",
    label: "Line tax 1",
    type: "number",
    entity: "saleLine",
    group: "Sale line tax",
    grains: LINE_ONLY,
    format: "currency",
  }),
  f({
    key: "line.calcTax2",
    path: "line.calcTax2",
    label: "Line tax 2",
    type: "number",
    entity: "saleLine",
    group: "Sale line tax",
    grains: LINE_ONLY,
    format: "currency",
  }),
  f({
    key: "line.taxClassID",
    path: "line.taxClassID",
    label: "Line tax class ID",
    type: "text",
    entity: "saleLine",
    group: "Sale line tax",
    grains: LINE_ONLY,
    idLike: true,
  }),
  f({
    key: "line.taxCategoryID",
    path: "line.taxCategoryID",
    label: "Line tax category ID",
    type: "text",
    entity: "saleLine",
    group: "Sale line tax",
    grains: LINE_ONLY,
    idLike: true,
  }),

  // ── Sale line cost ─────────────────────────────────────────
  f({
    key: "line.avgCost",
    path: "line.avgCost",
    label: "Line average cost",
    type: "number",
    entity: "saleLine",
    group: "Sale line cost",
    grains: LINE_ONLY,
    format: "currency",
  }),
  f({
    key: "line.fifoCost",
    path: "line.fifoCost",
    label: "Line FIFO cost",
    type: "number",
    entity: "saleLine",
    group: "Sale line cost",
    grains: LINE_ONLY,
    format: "currency",
  }),

  // ── Sale line flags ────────────────────────────────────────
  f({
    key: "line.isLayaway",
    path: "line.isLayaway",
    label: "Layaway",
    type: "boolean",
    entity: "saleLine",
    group: "Sale line flags",
    grains: LINE_ONLY,
  }),
  f({
    key: "line.isWorkorder",
    path: "line.isWorkorder",
    label: "Workorder line",
    type: "boolean",
    entity: "saleLine",
    group: "Sale line flags",
    grains: LINE_ONLY,
  }),
  f({
    key: "line.isSpecialOrder",
    path: "line.isSpecialOrder",
    label: "Special order",
    type: "boolean",
    entity: "saleLine",
    group: "Sale line flags",
    grains: LINE_ONLY,
  }),

  // ── Sale line links ────────────────────────────────────────
  f({
    key: "line.itemID",
    path: "line.itemID",
    label: "Item ID",
    type: "text",
    entity: "saleLine",
    group: "Sale line links",
    grains: LINE_ONLY,
    idLike: true,
  }),
  f({
    key: "line.employeeID",
    path: "line.employeeID",
    label: "Line employee ID",
    type: "text",
    entity: "saleLine",
    group: "Sale line links",
    grains: LINE_ONLY,
    idLike: true,
  }),
  f({
    key: "line.customerID",
    path: "line.customerID",
    label: "Line customer ID",
    description: "Customer ID on layaway / special order / workorder lines.",
    type: "text",
    entity: "saleLine",
    group: "Sale line links",
    grains: LINE_ONLY,
    idLike: true,
  }),
  f({
    key: "line.shopID",
    path: "line.shopID",
    label: "Line shop ID",
    type: "text",
    entity: "saleLine",
    group: "Sale line links",
    grains: LINE_ONLY,
    idLike: true,
  }),
  f({
    key: "line.noteID",
    path: "line.noteID",
    label: "Line note ID",
    type: "text",
    entity: "saleLine",
    group: "Sale line links",
    grains: LINE_ONLY,
    idLike: true,
  }),
  f({
    key: "line.parentSaleLineID",
    path: "line.parentSaleLineID",
    label: "Parent sale line ID",
    description: "Original line for refunds, or parent for item fees.",
    type: "text",
    entity: "saleLine",
    group: "Sale line links",
    grains: LINE_ONLY,
    idLike: true,
  }),
  f({
    key: "line.itemFeeID",
    path: "line.itemFeeID",
    label: "Item fee ID",
    type: "text",
    entity: "saleLine",
    group: "Sale line links",
    grains: LINE_ONLY,
    idLike: true,
  }),

  // ── Line note ──────────────────────────────────────────────
  f({
    key: "line.note",
    path: "line.note",
    label: "Line note",
    description: "Note text attached to the sale line (prints on receipt).",
    type: "text",
    entity: "note",
    group: "Sale line note",
    grains: LINE_ONLY,
  }),

  // ── Item fee ───────────────────────────────────────────────
  f({
    key: "line.itemFeeName",
    path: "line.itemFeeName",
    label: "Item fee name",
    type: "text",
    entity: "itemFee",
    group: "Item fee",
    grains: LINE_ONLY,
  }),
  f({
    key: "line.itemFeeValue",
    path: "line.itemFeeValue",
    label: "Item fee value",
    type: "number",
    entity: "itemFee",
    group: "Item fee",
    grains: LINE_ONLY,
    format: "currency",
  }),

  // ── Item (from SaleLines.Item) ─────────────────────────────
  f({
    key: "item.description",
    path: "item.description",
    label: "Item description",
    type: "text",
    entity: "item",
    group: "Item",
    grains: LINE_ONLY,
  }),
  f({
    key: "item.systemSku",
    path: "item.systemSku",
    label: "System SKU",
    type: "text",
    entity: "item",
    group: "Item",
    grains: LINE_ONLY,
    idLike: true,
  }),
  f({
    key: "item.customSku",
    path: "item.customSku",
    label: "Custom SKU",
    type: "text",
    entity: "item",
    group: "Item",
    grains: LINE_ONLY,
    idLike: true,
  }),
  f({
    key: "item.manufacturerSku",
    path: "item.manufacturerSku",
    label: "Manufacturer SKU",
    type: "text",
    entity: "item",
    group: "Item",
    grains: LINE_ONLY,
    idLike: true,
  }),
  f({
    key: "item.upc",
    path: "item.upc",
    label: "UPC",
    type: "text",
    entity: "item",
    group: "Item",
    grains: LINE_ONLY,
    idLike: true,
  }),
  f({
    key: "item.ean",
    path: "item.ean",
    label: "EAN",
    type: "text",
    entity: "item",
    group: "Item",
    grains: LINE_ONLY,
    idLike: true,
  }),
  f({
    key: "item.itemType",
    path: "item.itemType",
    label: "Item type",
    type: "text",
    entity: "item",
    group: "Item",
    grains: LINE_ONLY,
  }),
  f({
    key: "item.modelYear",
    path: "item.modelYear",
    label: "Model year",
    type: "text",
    entity: "item",
    group: "Item",
    grains: LINE_ONLY,
  }),
  f({
    key: "item.categoryID",
    path: "item.categoryID",
    label: "Item category ID",
    type: "text",
    entity: "item",
    group: "Item",
    grains: LINE_ONLY,
    idLike: true,
  }),
  f({
    key: "item.manufacturerID",
    path: "item.manufacturerID",
    label: "Manufacturer ID",
    type: "text",
    entity: "item",
    group: "Item",
    grains: LINE_ONLY,
    idLike: true,
  }),
  f({
    key: "item.defaultVendorID",
    path: "item.defaultVendorID",
    label: "Default vendor ID",
    type: "text",
    entity: "item",
    group: "Item",
    grains: LINE_ONLY,
    idLike: true,
  }),
  f({
    key: "item.defaultCost",
    path: "item.defaultCost",
    label: "Item default cost",
    type: "number",
    entity: "item",
    group: "Item",
    grains: LINE_ONLY,
    format: "currency",
  }),
  f({
    key: "item.avgCost",
    path: "item.avgCost",
    label: "Item average cost",
    type: "number",
    entity: "item",
    group: "Item",
    grains: LINE_ONLY,
    format: "currency",
  }),
  f({
    key: "item.archived",
    path: "item.archived",
    label: "Item archived",
    type: "boolean",
    entity: "item",
    group: "Item",
    grains: LINE_ONLY,
  }),
  f({
    key: "item.serialized",
    path: "item.serialized",
    label: "Item serialised",
    type: "boolean",
    entity: "item",
    group: "Item",
    grains: LINE_ONLY,
  }),
  f({
    key: "item.discountable",
    path: "item.discountable",
    label: "Item discountable",
    type: "boolean",
    entity: "item",
    group: "Item",
    grains: LINE_ONLY,
  }),
  f({
    key: "item.publishToEcom",
    path: "item.publishToEcom",
    label: "Published to ecom",
    type: "boolean",
    entity: "item",
    group: "Item",
    grains: LINE_ONLY,
  }),

  // ── Customer (from Sale.Customer) ──────────────────────────
  f({
    key: "customer.customerID",
    path: "customer.customerID",
    label: "Customer ID",
    type: "text",
    entity: "customer",
    group: "Customer",
    idLike: true,
  }),
  f({
    key: "customer.firstName",
    path: "customer.firstName",
    label: "Customer first name",
    type: "text",
    entity: "customer",
    group: "Customer",
  }),
  f({
    key: "customer.lastName",
    path: "customer.lastName",
    label: "Customer last name",
    type: "text",
    entity: "customer",
    group: "Customer",
  }),
  f({
    key: "customer.fullName",
    path: "customer.fullName",
    label: "Customer full name",
    description: "firstName + lastName.",
    type: "text",
    entity: "customer",
    group: "Customer",
  }),
  f({
    key: "customer.title",
    path: "customer.title",
    label: "Customer title",
    type: "text",
    entity: "customer",
    group: "Customer",
  }),
  f({
    key: "customer.company",
    path: "customer.company",
    label: "Customer company",
    type: "text",
    entity: "customer",
    group: "Customer",
  }),
  f({
    key: "customer.email",
    path: "customer.email",
    label: "Customer email",
    description: "Primary email from Contact.Emails.",
    type: "text",
    entity: "customer",
    group: "Customer",
  }),
  f({
    key: "customer.phone",
    path: "customer.phone",
    label: "Customer phone",
    description: "Best available phone from Contact.",
    type: "text",
    entity: "customer",
    group: "Customer",
  }),
  f({
    key: "customer.archived",
    path: "customer.archived",
    label: "Customer archived",
    type: "boolean",
    entity: "customer",
    group: "Customer",
  }),
  f({
    key: "customer.customerTypeID",
    path: "customer.customerTypeID",
    label: "Customer type ID",
    type: "text",
    entity: "customer",
    group: "Customer",
    idLike: true,
  }),
  f({
    key: "customer.creditAccountID",
    path: "customer.creditAccountID",
    label: "Customer credit account ID",
    type: "text",
    entity: "customer",
    group: "Customer",
    idLike: true,
  }),

  // ── Payments (sale-level summary; duplicated on each line) ─
  f({
    key: "payment.count",
    path: "payment.count",
    label: "Payment count",
    description: "Number of payments on the sale.",
    type: "number",
    entity: "salePayment",
    group: "Payments",
    format: "number",
  }),
  f({
    key: "payment.totalAmount",
    path: "payment.totalAmount",
    label: "Payment total",
    description: "Sum of payment amounts on the sale.",
    type: "number",
    entity: "salePayment",
    group: "Payments",
    format: "currency",
  }),
  f({
    key: "payment.totalTips",
    path: "payment.totalTips",
    label: "Payment tips total",
    type: "number",
    entity: "salePayment",
    group: "Payments",
    format: "currency",
  }),
  f({
    key: "payment.types",
    path: "payment.types",
    label: "Payment types",
    description: "Comma-separated payment type names.",
    type: "text",
    entity: "salePayment",
    group: "Payments",
  }),
  f({
    key: "payment.firstAmount",
    path: "payment.firstAmount",
    label: "First payment amount",
    type: "number",
    entity: "salePayment",
    group: "Payments",
    format: "currency",
  }),
  f({
    key: "payment.firstType",
    path: "payment.firstType",
    label: "First payment type",
    type: "text",
    entity: "salePayment",
    group: "Payments",
  }),
  f({
    key: "payment.firstPaymentTypeID",
    path: "payment.firstPaymentTypeID",
    label: "First payment type ID",
    type: "text",
    entity: "salePayment",
    group: "Payments",
    idLike: true,
  }),

  // ── Sale-grain helpers ─────────────────────────────────────
  f({
    key: "sale.lineCount",
    path: "sale.lineCount",
    label: "Line count",
    description: "Number of sale lines on the sale.",
    type: "number",
    entity: "sale",
    group: "Sale identity",
    grains: SALE_ONLY,
    format: "number",
  }),
];

const FIELD_BY_KEY = new Map(SALES_TABLE_FIELDS.map((field) => [field.key, field]));

export function getSalesField(key: string): TableBuilderField | undefined {
  return FIELD_BY_KEY.get(key);
}

export function getSalesFieldsForGrain(grain: TableBuilderGrain): TableBuilderField[] {
  return SALES_TABLE_FIELDS.filter((field) => field.grains.includes(grain));
}

export function groupSalesFields(
  fields: TableBuilderField[],
): Array<{ group: string; fields: TableBuilderField[] }> {
  const order: string[] = [];
  const map = new Map<string, TableBuilderField[]>();

  for (const field of fields) {
    if (!map.has(field.group)) {
      map.set(field.group, []);
      order.push(field.group);
    }
    map.get(field.group)!.push(field);
  }

  return order.map((group) => ({ group, fields: map.get(group)! }));
}

/** Sensible starter columns for a sales line table. */
export const DEFAULT_SALES_LINE_COLUMNS = [
  "sale.completeTime",
  "sale.ticketNumber",
  "customer.fullName",
  "item.description",
  "item.systemSku",
  "line.unitQuantity",
  "line.unitPrice",
  "line.calcSubtotal",
  "line.calcTotal",
  "sale.employeeID",
] as const;

export const DEFAULT_SALES_COLUMNS = [
  "sale.completeTime",
  "sale.ticketNumber",
  "customer.fullName",
  "sale.calcSubtotal",
  "sale.calcDiscount",
  "sale.total",
  "sale.calcPayments",
  "payment.types",
  "sale.lineCount",
  "sale.employeeID",
] as const;
