-- ============================================================
-- Product Images Table
-- ============================================================
-- Stores images for canonical products with multiple variants and formats

CREATE TABLE IF NOT EXISTS product_images (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  
  -- Link to canonical product
  canonical_product_id UUID NOT NULL REFERENCES canonical_products(id) ON DELETE CASCADE,
  
  -- Storage information
  storage_path TEXT NOT NULL, -- Original image path in Supabase Storage
  is_primary BOOLEAN DEFAULT false,
  sort_order INTEGER DEFAULT 0,
  
  -- Image variants (auto-generated by processing pipeline)
  -- Structure: { "thumbnail": "path/to/thumb.webp", "small": "path/to/small.webp", ... }
  variants JSONB DEFAULT '{}'::jsonb,
  
  -- Format variants (auto-generated)
  -- Structure: { "webp": {...sizes}, "avif": {...sizes}, "jpeg": {...sizes} }
  formats JSONB DEFAULT '{}'::jsonb,
  
  -- Image metadata
  width INTEGER,
  height INTEGER,
  file_size INTEGER,
  mime_type TEXT,
  
  -- Upload tracking
  uploaded_by UUID REFERENCES auth.users(id),
  
  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- Indexes
-- ============================================================

-- Primary lookup by canonical product
CREATE INDEX IF NOT EXISTS idx_product_images_canonical 
  ON product_images(canonical_product_id);

-- Find primary image quickly
CREATE INDEX IF NOT EXISTS idx_product_images_primary 
  ON product_images(canonical_product_id, is_primary) 
  WHERE is_primary = true;

-- Sort order for galleries
CREATE INDEX IF NOT EXISTS idx_product_images_sort 
  ON product_images(canonical_product_id, sort_order);

-- Uploaded by user (for tracking)
CREATE INDEX IF NOT EXISTS idx_product_images_uploaded_by 
  ON product_images(uploaded_by);

-- ============================================================
-- Enable RLS
-- ============================================================
ALTER TABLE product_images ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- RLS Policies
-- ============================================================

-- Anyone can view product images (needed for marketplace)
CREATE POLICY "Public can view product images"
  ON product_images FOR SELECT
  USING (true);

-- Authenticated users can insert images
CREATE POLICY "Authenticated users can insert product images"
  ON product_images FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Users can update images they uploaded or any if they're admin
CREATE POLICY "Users can update product images"
  ON product_images FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Users can delete images they uploaded or service role
CREATE POLICY "Users can delete own product images"
  ON product_images FOR DELETE
  TO authenticated
  USING (uploaded_by = auth.uid());

CREATE POLICY "Service role can delete any product images"
  ON product_images FOR DELETE
  TO service_role
  USING (true);

-- ============================================================
-- Trigger for updated_at
-- ============================================================
CREATE TRIGGER update_product_images_updated_at
  BEFORE UPDATE ON product_images
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- Function: Update Primary Image
-- ============================================================
-- Ensures only one primary image per canonical product
CREATE OR REPLACE FUNCTION set_primary_image()
RETURNS TRIGGER AS $$
BEGIN
  -- If this image is being set as primary
  IF NEW.is_primary = true THEN
    -- Set all other images for this product to non-primary
    UPDATE product_images 
    SET is_primary = false 
    WHERE canonical_product_id = NEW.canonical_product_id 
      AND id != NEW.id
      AND is_primary = true;
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER enforce_single_primary_image
  BEFORE INSERT OR UPDATE ON product_images
  FOR EACH ROW
  EXECUTE FUNCTION set_primary_image();

-- ============================================================
-- Function: Update Image Count on Canonical Product
-- ============================================================
CREATE OR REPLACE FUNCTION update_canonical_image_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE canonical_products 
    SET image_count = image_count + 1 
    WHERE id = NEW.canonical_product_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE canonical_products 
    SET image_count = GREATEST(0, image_count - 1)
    WHERE id = OLD.canonical_product_id;
  END IF;
  
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_image_count_on_insert
  AFTER INSERT ON product_images
  FOR EACH ROW
  EXECUTE FUNCTION update_canonical_image_count();

CREATE TRIGGER update_image_count_on_delete
  AFTER DELETE ON product_images
  FOR EACH ROW
  EXECUTE FUNCTION update_canonical_image_count();

-- ============================================================
-- Comments for Documentation
-- ============================================================
COMMENT ON TABLE product_images IS 'Stores product images with multiple size and format variants for optimal performance';
COMMENT ON COLUMN product_images.variants IS 'JSONB containing paths to different size variants (thumbnail, small, medium, large, original)';
COMMENT ON COLUMN product_images.formats IS 'JSONB containing paths to different format variants (webp, avif, jpeg) for each size';
COMMENT ON COLUMN product_images.is_primary IS 'Only one image per canonical product can be primary';










