-- Add is_ai_generated column to product_images table
-- This identifies images that were created by AI transformation

ALTER TABLE product_images
ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN DEFAULT FALSE;

-- Create index for quick lookups
CREATE INDEX IF NOT EXISTS idx_product_images_ai_generated 
  ON product_images(is_ai_generated) 
  WHERE is_ai_generated = TRUE;

COMMENT ON COLUMN product_images.is_ai_generated IS 'True if this image was generated by AI (e.g., background removal/optimization)';

