// Genie Lightspeed SQL surface: view names, RPC, limits, and column schemas.
const GENIE_LIGHTSPEED_SQL_VIEW = 'genie_lightspeed_sales_report_lines'
const GENIE_LIGHTSPEED_INVENTORY_SQL_VIEW = 'genie_lightspeed_inventory'
const GENIE_LIGHTSPEED_SQL_RPC = 'execute_lightspeed_genie_sql'
const GENIE_LIGHTSPEED_SQL_DEFAULT_LIMIT = 500
const GENIE_LIGHTSPEED_SQL_MAX_LIMIT = 1000
const GENIE_LIGHTSPEED_SQL_FALLBACK_MAX_LINES = 10_000
const DEPRECATED_LIGHTSPEED_ANALYTICAL_TOOL_NAMES = new Set([
  'get_lightspeed_sales_summary',
  'get_lightspeed_sales_list',
  'get_lightspeed_sales_timeseries',
  'get_lightspeed_top_sold_products',
  'get_lightspeed_sold_product_timeseries',
  'search_lightspeed_customers',
  'get_lightspeed_product_purchasers',
  'get_lightspeed_customer_profile',
  'get_lightspeed_customer_sales',
  'get_lightspeed_top_customers',
])

const GENIE_LIGHTSPEED_SQL_SCHEMA = [
  'sale_id text',
  'sale_line_id text',
  'ticket_number text',
  'complete_time timestamptz',
  'line_time timestamptz',
  'employee_id text',
  'employee_name text',
  'category_id text',
  'category text',
  'item_id text',
  'sku text',
  'description text',
  'quantity numeric',
  'retail numeric',
  'subtotal numeric',
  'discount numeric',
  'total numeric',
  'customer_id text',
  'customer_full_name text',
  'cost numeric',
  'profit numeric',
  'margin_pct numeric',
  'synced_at timestamptz',
  'created_at timestamptz',
  'updated_at timestamptz',
]

const GENIE_LIGHTSPEED_INVENTORY_SQL_SCHEMA = [
  'item_id text',
  'account_id text',
  'product_uuid text',
  'system_sku text',
  'custom_sku text',
  'manufacturer_sku text',
  'upc text',
  'ean text',
  'name text',
  'description text',
  'model_year text',
  'item_type text',
  'labor_duration_minutes numeric',
  'brand_id text',
  'brand_name text',
  'category_id text',
  'category_name text',
  'category_path text',
  'supplier_id text',
  'supplier_name text',
  'supplier_archived boolean',
  'supplier_currency_code text',
  'default_price numeric',
  'online_price numeric',
  'msrp numeric',
  'default_cost numeric',
  'avg_cost numeric',
  'total_qoh numeric',
  'total_sellable numeric',
  'backorder numeric',
  'component_qoh numeric',
  'component_backorder numeric',
  'reorder_point numeric',
  'reorder_level numeric',
  'on_layaway numeric',
  'on_special_order numeric',
  'on_workorder numeric',
  'on_transfer_in numeric',
  'on_transfer_out numeric',
  'is_in_stock boolean',
  'archived boolean',
  'publish_to_ecom boolean',
  'serialized boolean',
  'discountable boolean',
  'taxable boolean',
  'tax_class_id text',
  'tax_class_name text',
  'department_id text',
  'season_id text',
  'default_vendor_id text',
  'item_matrix_id text',
  'primary_image_url text',
  'images jsonb',
  'prices jsonb',
  'stock_data jsonb',
  'lightspeed_created_at timestamptz',
  'lightspeed_updated_at timestamptz',
  'inventory_updated_at timestamptz',
  'first_seen_at timestamptz',
  'last_seen_at timestamptz',
  'last_synced_at timestamptz',
  'created_at timestamptz',
  'updated_at timestamptz',
]

const GENIE_LIGHTSPEED_SQL_AVAILABLE_COLUMNS = {
  [GENIE_LIGHTSPEED_SQL_VIEW]: GENIE_LIGHTSPEED_SQL_SCHEMA,
  [GENIE_LIGHTSPEED_INVENTORY_SQL_VIEW]: GENIE_LIGHTSPEED_INVENTORY_SQL_SCHEMA,
}

export {
  GENIE_LIGHTSPEED_SQL_VIEW,
  GENIE_LIGHTSPEED_INVENTORY_SQL_VIEW,
  GENIE_LIGHTSPEED_SQL_RPC,
  GENIE_LIGHTSPEED_SQL_DEFAULT_LIMIT,
  GENIE_LIGHTSPEED_SQL_MAX_LIMIT,
  GENIE_LIGHTSPEED_SQL_FALLBACK_MAX_LINES,
  DEPRECATED_LIGHTSPEED_ANALYTICAL_TOOL_NAMES,
  GENIE_LIGHTSPEED_SQL_SCHEMA,
  GENIE_LIGHTSPEED_INVENTORY_SQL_SCHEMA,
  GENIE_LIGHTSPEED_SQL_AVAILABLE_COLUMNS,
}
